/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddMoneyRouteImport } from './routes/add-money'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsTermsRouteImport } from './routes/settings.terms'
import { Route as SettingsSchoolRouteImport } from './routes/settings.school'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsLanguageRouteImport } from './routes/settings.language'
import { Route as SettingsHelpRouteImport } from './routes/settings.help'
import { Route as SettingsFeedbackRouteImport } from './routes/settings.feedback'
import { Route as SettingsContactRouteImport } from './routes/settings.contact'
import { Route as SettingsChangePinRouteImport } from './routes/settings.change-pin'
import { Route as SettingsChangePasswordRouteImport } from './routes/settings.change-password'
import { Route as PaymentsCallbackRouteImport } from './routes/payments.callback'
import { Route as GuardianProfileRouteImport } from './routes/guardian.profile'
import { Route as GuardianForgotPasswordRouteImport } from './routes/guardian.forgot-password'
import { Route as GuardianAuthRouteImport } from './routes/guardian.auth'
import { Route as AddMoneyTelecelRouteImport } from './routes/add-money.telecel'
import { Route as AddMoneyMtnRouteImport } from './routes/add-money.mtn'
import { Route as AddMoneyAirteltigoRouteImport } from './routes/add-money.airteltigo'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMoneyRoute = AddMoneyRouteImport.update({
  id: '/add-money',
  path: '/add-money',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTermsRoute = SettingsTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSchoolRoute = SettingsSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHelpRoute = SettingsHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFeedbackRoute = SettingsFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsContactRoute = SettingsContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsChangePinRoute = SettingsChangePinRouteImport.update({
  id: '/change-pin',
  path: '/change-pin',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsChangePasswordRoute = SettingsChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => SettingsRoute,
} as any)
const PaymentsCallbackRoute = PaymentsCallbackRouteImport.update({
  id: '/payments/callback',
  path: '/payments/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianProfileRoute = GuardianProfileRouteImport.update({
  id: '/guardian/profile',
  path: '/guardian/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianForgotPasswordRoute = GuardianForgotPasswordRouteImport.update({
  id: '/guardian/forgot-password',
  path: '/guardian/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianAuthRoute = GuardianAuthRouteImport.update({
  id: '/guardian/auth',
  path: '/guardian/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMoneyTelecelRoute = AddMoneyTelecelRouteImport.update({
  id: '/telecel',
  path: '/telecel',
  getParentRoute: () => AddMoneyRoute,
} as any)
const AddMoneyMtnRoute = AddMoneyMtnRouteImport.update({
  id: '/mtn',
  path: '/mtn',
  getParentRoute: () => AddMoneyRoute,
} as any)
const AddMoneyAirteltigoRoute = AddMoneyAirteltigoRouteImport.update({
  id: '/airteltigo',
  path: '/airteltigo',
  getParentRoute: () => AddMoneyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-money': typeof AddMoneyRouteWithChildren
  '/admin': typeof AdminRoute
  '/insights': typeof InsightsRoute
  '/parent': typeof ParentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/student': typeof StudentRoute
  '/transactions': typeof TransactionsRoute
  '/vendor': typeof VendorRoute
  '/add-money/airteltigo': typeof AddMoneyAirteltigoRoute
  '/add-money/mtn': typeof AddMoneyMtnRoute
  '/add-money/telecel': typeof AddMoneyTelecelRoute
  '/guardian/auth': typeof GuardianAuthRoute
  '/guardian/forgot-password': typeof GuardianForgotPasswordRoute
  '/guardian/profile': typeof GuardianProfileRoute
  '/payments/callback': typeof PaymentsCallbackRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/settings/change-pin': typeof SettingsChangePinRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/school': typeof SettingsSchoolRoute
  '/settings/terms': typeof SettingsTermsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-money': typeof AddMoneyRouteWithChildren
  '/admin': typeof AdminRoute
  '/insights': typeof InsightsRoute
  '/parent': typeof ParentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRoute
  '/transactions': typeof TransactionsRoute
  '/vendor': typeof VendorRoute
  '/add-money/airteltigo': typeof AddMoneyAirteltigoRoute
  '/add-money/mtn': typeof AddMoneyMtnRoute
  '/add-money/telecel': typeof AddMoneyTelecelRoute
  '/guardian/auth': typeof GuardianAuthRoute
  '/guardian/forgot-password': typeof GuardianForgotPasswordRoute
  '/guardian/profile': typeof GuardianProfileRoute
  '/payments/callback': typeof PaymentsCallbackRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/settings/change-pin': typeof SettingsChangePinRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/school': typeof SettingsSchoolRoute
  '/settings/terms': typeof SettingsTermsRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-money': typeof AddMoneyRouteWithChildren
  '/admin': typeof AdminRoute
  '/insights': typeof InsightsRoute
  '/parent': typeof ParentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/student': typeof StudentRoute
  '/transactions': typeof TransactionsRoute
  '/vendor': typeof VendorRoute
  '/add-money/airteltigo': typeof AddMoneyAirteltigoRoute
  '/add-money/mtn': typeof AddMoneyMtnRoute
  '/add-money/telecel': typeof AddMoneyTelecelRoute
  '/guardian/auth': typeof GuardianAuthRoute
  '/guardian/forgot-password': typeof GuardianForgotPasswordRoute
  '/guardian/profile': typeof GuardianProfileRoute
  '/payments/callback': typeof PaymentsCallbackRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/settings/change-pin': typeof SettingsChangePinRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/school': typeof SettingsSchoolRoute
  '/settings/terms': typeof SettingsTermsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-money'
    | '/admin'
    | '/insights'
    | '/parent'
    | '/reset-password'
    | '/settings'
    | '/student'
    | '/transactions'
    | '/vendor'
    | '/add-money/airteltigo'
    | '/add-money/mtn'
    | '/add-money/telecel'
    | '/guardian/auth'
    | '/guardian/forgot-password'
    | '/guardian/profile'
    | '/payments/callback'
    | '/settings/change-password'
    | '/settings/change-pin'
    | '/settings/contact'
    | '/settings/feedback'
    | '/settings/help'
    | '/settings/language'
    | '/settings/privacy'
    | '/settings/school'
    | '/settings/terms'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-money'
    | '/admin'
    | '/insights'
    | '/parent'
    | '/reset-password'
    | '/student'
    | '/transactions'
    | '/vendor'
    | '/add-money/airteltigo'
    | '/add-money/mtn'
    | '/add-money/telecel'
    | '/guardian/auth'
    | '/guardian/forgot-password'
    | '/guardian/profile'
    | '/payments/callback'
    | '/settings/change-password'
    | '/settings/change-pin'
    | '/settings/contact'
    | '/settings/feedback'
    | '/settings/help'
    | '/settings/language'
    | '/settings/privacy'
    | '/settings/school'
    | '/settings/terms'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/add-money'
    | '/admin'
    | '/insights'
    | '/parent'
    | '/reset-password'
    | '/settings'
    | '/student'
    | '/transactions'
    | '/vendor'
    | '/add-money/airteltigo'
    | '/add-money/mtn'
    | '/add-money/telecel'
    | '/guardian/auth'
    | '/guardian/forgot-password'
    | '/guardian/profile'
    | '/payments/callback'
    | '/settings/change-password'
    | '/settings/change-pin'
    | '/settings/contact'
    | '/settings/feedback'
    | '/settings/help'
    | '/settings/language'
    | '/settings/privacy'
    | '/settings/school'
    | '/settings/terms'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddMoneyRoute: typeof AddMoneyRouteWithChildren
  AdminRoute: typeof AdminRoute
  InsightsRoute: typeof InsightsRoute
  ParentRoute: typeof ParentRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StudentRoute: typeof StudentRoute
  TransactionsRoute: typeof TransactionsRoute
  VendorRoute: typeof VendorRoute
  GuardianAuthRoute: typeof GuardianAuthRoute
  GuardianForgotPasswordRoute: typeof GuardianForgotPasswordRoute
  GuardianProfileRoute: typeof GuardianProfileRoute
  PaymentsCallbackRoute: typeof PaymentsCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-money': {
      id: '/add-money'
      path: '/add-money'
      fullPath: '/add-money'
      preLoaderRoute: typeof AddMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/terms': {
      id: '/settings/terms'
      path: '/terms'
      fullPath: '/settings/terms'
      preLoaderRoute: typeof SettingsTermsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/school': {
      id: '/settings/school'
      path: '/school'
      fullPath: '/settings/school'
      preLoaderRoute: typeof SettingsSchoolRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/help': {
      id: '/settings/help'
      path: '/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof SettingsHelpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/feedback': {
      id: '/settings/feedback'
      path: '/feedback'
      fullPath: '/settings/feedback'
      preLoaderRoute: typeof SettingsFeedbackRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/contact': {
      id: '/settings/contact'
      path: '/contact'
      fullPath: '/settings/contact'
      preLoaderRoute: typeof SettingsContactRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/change-pin': {
      id: '/settings/change-pin'
      path: '/change-pin'
      fullPath: '/settings/change-pin'
      preLoaderRoute: typeof SettingsChangePinRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/change-password': {
      id: '/settings/change-password'
      path: '/change-password'
      fullPath: '/settings/change-password'
      preLoaderRoute: typeof SettingsChangePasswordRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/payments/callback': {
      id: '/payments/callback'
      path: '/payments/callback'
      fullPath: '/payments/callback'
      preLoaderRoute: typeof PaymentsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/profile': {
      id: '/guardian/profile'
      path: '/guardian/profile'
      fullPath: '/guardian/profile'
      preLoaderRoute: typeof GuardianProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/forgot-password': {
      id: '/guardian/forgot-password'
      path: '/guardian/forgot-password'
      fullPath: '/guardian/forgot-password'
      preLoaderRoute: typeof GuardianForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/auth': {
      id: '/guardian/auth'
      path: '/guardian/auth'
      fullPath: '/guardian/auth'
      preLoaderRoute: typeof GuardianAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-money/telecel': {
      id: '/add-money/telecel'
      path: '/telecel'
      fullPath: '/add-money/telecel'
      preLoaderRoute: typeof AddMoneyTelecelRouteImport
      parentRoute: typeof AddMoneyRoute
    }
    '/add-money/mtn': {
      id: '/add-money/mtn'
      path: '/mtn'
      fullPath: '/add-money/mtn'
      preLoaderRoute: typeof AddMoneyMtnRouteImport
      parentRoute: typeof AddMoneyRoute
    }
    '/add-money/airteltigo': {
      id: '/add-money/airteltigo'
      path: '/airteltigo'
      fullPath: '/add-money/airteltigo'
      preLoaderRoute: typeof AddMoneyAirteltigoRouteImport
      parentRoute: typeof AddMoneyRoute
    }
  }
}

interface AddMoneyRouteChildren {
  AddMoneyAirteltigoRoute: typeof AddMoneyAirteltigoRoute
  AddMoneyMtnRoute: typeof AddMoneyMtnRoute
  AddMoneyTelecelRoute: typeof AddMoneyTelecelRoute
}

const AddMoneyRouteChildren: AddMoneyRouteChildren = {
  AddMoneyAirteltigoRoute: AddMoneyAirteltigoRoute,
  AddMoneyMtnRoute: AddMoneyMtnRoute,
  AddMoneyTelecelRoute: AddMoneyTelecelRoute,
}

const AddMoneyRouteWithChildren = AddMoneyRoute._addFileChildren(
  AddMoneyRouteChildren,
)

interface SettingsRouteChildren {
  SettingsChangePasswordRoute: typeof SettingsChangePasswordRoute
  SettingsChangePinRoute: typeof SettingsChangePinRoute
  SettingsContactRoute: typeof SettingsContactRoute
  SettingsFeedbackRoute: typeof SettingsFeedbackRoute
  SettingsHelpRoute: typeof SettingsHelpRoute
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsSchoolRoute: typeof SettingsSchoolRoute
  SettingsTermsRoute: typeof SettingsTermsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsChangePasswordRoute: SettingsChangePasswordRoute,
  SettingsChangePinRoute: SettingsChangePinRoute,
  SettingsContactRoute: SettingsContactRoute,
  SettingsFeedbackRoute: SettingsFeedbackRoute,
  SettingsHelpRoute: SettingsHelpRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsSchoolRoute: SettingsSchoolRoute,
  SettingsTermsRoute: SettingsTermsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddMoneyRoute: AddMoneyRouteWithChildren,
  AdminRoute: AdminRoute,
  InsightsRoute: InsightsRoute,
  ParentRoute: ParentRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StudentRoute: StudentRoute,
  TransactionsRoute: TransactionsRoute,
  VendorRoute: VendorRoute,
  GuardianAuthRoute: GuardianAuthRoute,
  GuardianForgotPasswordRoute: GuardianForgotPasswordRoute,
  GuardianProfileRoute: GuardianProfileRoute,
  PaymentsCallbackRoute: PaymentsCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
