/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuardianForgotPasswordRouteImport } from './routes/guardian.forgot-password'
import { Route as GuardianAuthRouteImport } from './routes/guardian.auth'

const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianForgotPasswordRoute = GuardianForgotPasswordRouteImport.update({
  id: '/guardian/forgot-password',
  path: '/guardian/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianAuthRoute = GuardianAuthRouteImport.update({
  id: '/guardian/auth',
  path: '/guardian/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parent': typeof ParentRoute
  '/guardian/auth': typeof GuardianAuthRoute
  '/guardian/forgot-password': typeof GuardianForgotPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parent': typeof ParentRoute
  '/guardian/auth': typeof GuardianAuthRoute
  '/guardian/forgot-password': typeof GuardianForgotPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parent': typeof ParentRoute
  '/guardian/auth': typeof GuardianAuthRoute
  '/guardian/forgot-password': typeof GuardianForgotPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/parent' | '/guardian/auth' | '/guardian/forgot-password'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/parent' | '/guardian/auth' | '/guardian/forgot-password'
  id:
    | '__root__'
    | '/'
    | '/parent'
    | '/guardian/auth'
    | '/guardian/forgot-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParentRoute: typeof ParentRoute
  GuardianAuthRoute: typeof GuardianAuthRoute
  GuardianForgotPasswordRoute: typeof GuardianForgotPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/forgot-password': {
      id: '/guardian/forgot-password'
      path: '/guardian/forgot-password'
      fullPath: '/guardian/forgot-password'
      preLoaderRoute: typeof GuardianForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/auth': {
      id: '/guardian/auth'
      path: '/guardian/auth'
      fullPath: '/guardian/auth'
      preLoaderRoute: typeof GuardianAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParentRoute: ParentRoute,
  GuardianAuthRoute: GuardianAuthRoute,
  GuardianForgotPasswordRoute: GuardianForgotPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
